version: 2.1
jobs:
  build-image:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
        IMAGE_NAME: quay.io/flurdy/flurdy.com-docs
    steps:
     - checkout
     - setup_remote_docker
     - run:
         name: Build Docker image
         command: docker build -t $IMAGE_NAME:latest .
     - run:
         name: Archive Docker image
         command: docker save -o image.tar $IMAGE_NAME
     - persist_to_workspace:
         root: .
         paths:
           - ./image.tar

  publish-image:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
        IMAGE_NAME: quay.io/flurdy/flurdy.com-docs
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          name: Load archived Docker image
          command: docker load -i image.tar
      - run:
          name: Upload to registry
          command: |
            echo "$DOCKER_PASSWORD" | docker login quay.io -u "$DOCKER_LOGIN" --password-stdin
            docker push $IMAGE_NAME:latest
            IMAGE_TAG="1.0.${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build-master:
    jobs:
      - build-image:
          requires:
            - build
          filters:
            branches:
              only: master
      - publish-image:
          requires:
            - build-image
          filters:
            branches:
              only: master
